apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ip-country-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ip-country-api.labels" . | nindent 4 }}
automountServiceAccountToken: false
