apiVersion: v2
name: ip-country-api
description: Cache-aside IP country lookup API for Kubernetes
type: application
version: 0.2.0
appVersion: 0.1.0
kubeVersion: ">=1.30.0-0 <1.37.0-0"
sources:
  - https://github.com/afshin-flw/arvan-ip-country-api
maintainers:
  - name: afshin-flw
